targetPort: 3000
ingress:
  enable: true
  host: claw-fev2-dev.whales-market.site

resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "2000Mi"
healthCheck:
  enable: true
  path: /api/health

authDocs: false
